org: theothertechlead
app: alexa-gas-prices
service: alexa-gas-prices

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

functions:
  gasPrices:
    handler: handler.hello
    events:
      - alexaSkill: amzn1.ask.skill.b1950752-46a5-4b68-8c67-d18750ba45c4

